import 'package:flutter/material.dart';

import '../extensions/iterable_extension.dart';
import '../widgets/cascade_picker.dart';
import 'picker_form_field.dart';

export '../widgets/cascade_picker.dart' show ValueMapper, DataWidgetBuilder;

/// 级联选择框表单
class TxCascadePickerFormField<T, V> extends TxPickerFormField<T, V> {
  TxCascadePickerFormField({
    required super.source,
    required super.labelMapper,
    required ValueMapper<T, List<T>?> childrenMapper,
    V? initialValue,
    T? initialData,
    super.valueMapper,
    super.subtitleBuilder,
    super.disabledWhen,
    super.itemBuilder,
    super.showSearchField,
    super.placeholder,
    super.listTileTheme,
    bool? parentCheckable,
    super.clearable,
    super.key,
    super.onSaved,
    super.validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.decoration,
    super.onChanged,
    super.required,
    super.readOnly,
    super.focusNode,
    super.hintText,
    super.bordered,
    super.maxLines,
    super.minLines,
    super.displayConfig,
    super.scrollConfig,
    super.label,
    super.labelText,
    super.actionsBuilder,
    super.trailingBuilder,
    super.leading,
    super.tileTheme,
  }) : super(
          initialData: source.getInitialData<V>(
            initialData: initialData,
            initialValue: initialValue,
            valueMapper: valueMapper,
            childrenMapper: childrenMapper,
          ),
          onPickTap: (context, initialData) => showCascadePicker<T, V>(
            context: context,
            source: source,
            labelMapper: labelMapper,
            valueMapper: valueMapper,
            childrenMapper: childrenMapper,
            disabledWhen: disabledWhen,
            initialData: initialData,
            parentCheckable: parentCheckable,
            subtitleBuilder: subtitleBuilder,
            itemBuilder: itemBuilder,
            listTileTheme: listTileTheme,
            placeholder: placeholder,
            title: labelText,
            showSearchField: showSearchField,
          ),
        );

  TxCascadePickerFormField.fromMapList({
    required List<Map> source,
    String? labelKey,
    String? valueKey,
    String? idKey,
    String? pidKey,
    String? rootId,
    Map? initialData,
    super.initialValue,
    DataWidgetBuilder<Map>? subtitleBuilder,
    ValueMapper<Map, bool>? disabledWhen,
    PickerItemBuilder<Map>? itemBuilder,
    super.showSearchField,
    super.placeholder,
    super.listTileTheme,
    bool? parentCheckable,
    super.readOnly,
    super.clearable,
    super.key,
    super.onSaved,
    FormFieldValidator<Map>? validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.decoration,
    super.onChanged,
    super.required,
    super.focusNode,
    super.hintText,
    super.bordered,
    super.maxLines,
    super.minLines,
    super.displayConfig,
    super.scrollConfig,
    super.label,
    super.labelText,
    super.actionsBuilder,
    super.trailingBuilder,
    super.leading,
    super.tileTheme,
  }) : super(
          source: source as List<T>,
          initialData: initialData as T?,
          subtitleBuilder: subtitleBuilder as DataWidgetBuilder<T>?,
          disabledWhen: disabledWhen as ValueMapper<T, bool>?,
          itemBuilder: itemBuilder as PickerItemBuilder<T>?,
          labelMapper: (data) => (data as Map)[labelKey ?? kLabelKey],
          valueMapper: (data) =>
              (data as Map)[valueKey ?? labelKey ?? kLabelKey],
          onPickTap: ((context, initialData) => showMapListCascadePicker<V>(
                context: context,
                source: source,
                labelKey: labelKey,
                valueKey: valueKey,
                rootId: rootId,
                idKey: idKey,
                pidKey: pidKey,
                initialData: initialData as Map?,
                parentCheckable: parentCheckable,
                disabledWhen: disabledWhen,
                itemBuilder: itemBuilder,
                listTileTheme: listTileTheme,
                placeholder: placeholder,
                subtitleBuilder: subtitleBuilder,
                showSearchField: showSearchField,
                title: labelText,
              )) as PickVoidCallback<T>?,
          validator: validator as FormFieldValidator<T>?,
        );
}
