import 'package:flutter/material.dart';

import '../extensions/datetime_range_extension.dart';
import '../widgets/datetime_range_picker.dart';
import 'picker_form_field.dart';

const String _defaultFormat = 'yyyy/MM/dd HH:mm\t——\tyyyy/MM/dd HH:mm';

/// 日期+时间范围选择组件
@Deprecated(
  'Use TxDatetimeRangePickerFormFieldTile instead. '
  'This feature was deprecated after v0.3.0.',
)
class DatetimeRangePickerFormField extends TxDatetimeRangePickerFormFieldTile {
  @Deprecated(
    'Use TxDatetimeRangePickerFormFieldTile instead. '
    'This feature was deprecated after v0.3.0.',
  )
  DatetimeRangePickerFormField({
    super.format = 'yyyy-MM-dd HH:mm',
    super.firstDate,
    super.lastDate,
    super.helpText,
    super.key,
    super.required,
    Widget? label,
    super.labelText,
    Color? backgroundColor,
    Axis? direction,
    super.padding,
    super.actions,
    super.labelStyle,
    super.horizontalGap,
    super.minLabelWidth,
    super.onSaved,
    super.validator,
    DateTimeRange? initialValue,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.decoration,
    super.style,
    super.strutStyle,
    super.textDirection,
    super.textAlign,
    super.textAlignVertical,
    super.contextMenuBuilder,
    super.onChanged,
  }) : super(
          labelBuilder: label == null ? null : (context) => label,
          tileColor: backgroundColor,
          layoutDirection: direction,
          initialDatetimeRange: initialValue,
        );
}

/// [builder] 构建组件为日期时间范围选择框的 [FormField]
class TxDatetimeRangePickerFormField
    extends TxPickerFormField<DateTimeRange, String> {
  TxDatetimeRangePickerFormField({
    DateTimeRange? initialDatetimeRange,
    DateTime? firstDate,
    DateTime? lastDate,
    String? helpText,
    String? titleText,
    String? format,
    super.key,
    super.controller,
    super.focusNode,
    super.undoController,
    super.decoration,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textAlignVertical,
    super.textDirection,
    super.showCursor,
    super.autofocus,
    super.statesController,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onChanged,
    super.onEditingComplete,
    super.onFieldSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.cursorErrorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onTapAlwaysCalled,
    super.onTapOutside,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contextMenuBuilder,
    super.canRequestFocus,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
    super.onSaved,
    super.validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.required,
  }) : super.custom(
          initialValue: initialDatetimeRange,
          onPickTap: (context, range) => showDatetimeRangePicker(
            context,
            firstDate: firstDate,
            lastDate: lastDate,
            initialDatetimeRange: range,
            noticeText: helpText,
            title: titleText,
          ),
          displayTextMapper: (context, range) =>
              range.format(format ?? _defaultFormat),
        );
}

/// [field] 为日期时间范围选择框表单的 [TxPickerFormFieldTile]
class TxDatetimeRangePickerFormFieldTile
    extends TxPickerFormFieldTile<DateTimeRange, DateTimeRange> {
  TxDatetimeRangePickerFormFieldTile({
    DateTimeRange? initialDatetimeRange,
    DateTime? firstDate,
    DateTime? lastDate,
    String? helpText,
    String? titleText,
    String? format,
    super.labelBuilder,
    super.labelText,
    super.padding,
    super.actions,
    super.labelStyle,
    super.horizontalGap,
    super.tileColor,
    super.layoutDirection,
    super.trailing,
    super.leading,
    super.visualDensity,
    super.shape,
    super.iconColor,
    super.textColor,
    super.leadingAndTrailingTextStyle,
    super.minLeadingWidth,
    super.minLabelWidth,
    super.minVerticalPadding,
    super.dense,
    super.key,
    super.controller,
    super.focusNode,
    super.undoController,
    super.decoration,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textAlignVertical,
    super.textDirection,
    super.showCursor,
    super.autofocus,
    super.statesController,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onChanged,
    super.onEditingComplete,
    super.onFieldSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.cursorErrorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onTapAlwaysCalled,
    super.onTapOutside,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contextMenuBuilder,
    super.canRequestFocus,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
    super.onSaved,
    super.validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.required,
  }) : super.custom(
          initialValue: initialDatetimeRange,
          onPickTap: (context, range) => showDatetimeRangePicker(
            context,
            firstDate: firstDate,
            lastDate: lastDate,
            initialDatetimeRange: range,
            noticeText: helpText,
            title: titleText,
          ),
          displayTextMapper: (context, range) =>
              range.format(format ?? _defaultFormat),
        );
}
