import 'package:flutter/material.dart';

import '../widgets/multi_cascade_picker.dart';
import 'multi_picker_form_field.dart';

export '../widgets/multi_cascade_picker.dart'
    show
        ValueMapper,
        DataWidgetBuilder,
        MultiPickerItemBuilder,
        MultiPickerActionBarBuilder,
        MultiPickerSelectedItemBuilder,
        FilterMatcher,
        EqualityMatcher;

/// 级联多项选择配置
class TxMultiCascadePickerConfig<T> extends TxMultiPickerConfig<T> {
  const TxMultiCascadePickerConfig({
    super.subtitleBuilder,
    super.itemBuilder,
    super.disabledWhen,
    super.showSearchField,
    super.placeholder,
    super.listTileTheme,
    super.filterMatcher,
    super.equalityMatcher,
    super.secondaryBuilder,
    super.actionBarBuilder,
    super.selectedItemBuilder,
    this.parentCheckable,
    this.linkage,
  });

  final bool? parentCheckable;
  final bool? linkage;
}

/// 级联选择框表单
class TxMultiCascadePickerFormField<T, V> extends TxMultiPickerFormField<T, V> {
  TxMultiCascadePickerFormField({
    required super.source,
    required super.labelMapper,
    required ValueMapper<T, List<T>?> childrenMapper,
    super.valueMapper,
    super.initialData,
    super.initialValue,
    super.maxCount,
    super.minCount,
    TxMultiCascadePickerConfig<T>? super.pickerConfig,
    super.disabledWhen,
    super.readOnly,
    super.key,
    super.onSaved,
    super.validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.decoration,
    super.onChanged,
    super.required,
    super.focusNode,
    super.hintText,
    super.textAlign,
    super.bordered,
    super.canRequestFocus,
    super.label,
    super.labelText,
    super.actionsBuilder,
    super.trailingBuilder,
    super.leading,
  }) : super(
          onPickTap: (context, initialData) => showMultiCascadePicker<T>(
            title: labelText,
            context: context,
            source: source ?? [],
            labelMapper: labelMapper,
            childrenMapper: childrenMapper,
            initialData: initialData,
            parentCheckable: pickerConfig?.parentCheckable,
            itemBuilder: pickerConfig?.itemBuilder,
            listTileTheme: pickerConfig?.listTileTheme,
            placeholder: pickerConfig?.placeholder,
            maxCount: maxCount,
            linkage: pickerConfig?.linkage,
            actionBarBuilder: pickerConfig?.actionBarBuilder,
            selectedItemBuilder: pickerConfig?.selectedItemBuilder,
            showSearchField: pickerConfig?.showSearchField,
            subtitleBuilder: pickerConfig?.subtitleBuilder,
            disabledWhen: disabledWhen,
            filterMatcher: pickerConfig?.filterMatcher,
            equalityMatcher: pickerConfig?.equalityMatcher,
            secondaryBuilder: pickerConfig?.secondaryBuilder,
          ),
        );

  TxMultiCascadePickerFormField.fromMapList({
    required List<Map> source,
    String? labelKey,
    String? valueKey,
    String? idKey,
    String? pidKey,
    String? rootId,
    List<Map>? initialData,
    super.initialValue,
    TxMultiCascadePickerConfig<Map>? pickerConfig,
    super.maxCount,
    super.minCount,
    ValueMapper<Map, bool>? disabledWhen,
    super.readOnly,
    super.key,
    super.onSaved,
    FormFieldValidator<List<Map>>? validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.decoration,
    super.onChanged,
    super.required,
    super.focusNode,
    super.hintText,
    super.textAlign,
    super.bordered,
    super.canRequestFocus,
    super.label,
    super.labelText,
    super.actionsBuilder,
    super.trailingBuilder,
    super.leading,
  }) : super(
          source: source as List<T>,
          labelMapper: (val) => (val as Map)[labelKey],
          initialData: initialData as List<T>?,
          onPickTap: (context, initialData) => showMultiMapListCascadePicker<V>(
            title: labelText,
            context: context,
            source: source,
            labelKey: labelKey,
            idKey: idKey,
            pidKey: pidKey,
            rootId: rootId,
            initialData: initialData?.cast<Map>(),
            parentCheckable: pickerConfig?.parentCheckable,
            itemBuilder: pickerConfig?.itemBuilder,
            listTileTheme: pickerConfig?.listTileTheme,
            placeholder: pickerConfig?.placeholder,
            maxCount: maxCount,
            linkage: pickerConfig?.linkage,
            actionBarBuilder: pickerConfig?.actionBarBuilder,
            selectedItemBuilder: pickerConfig?.selectedItemBuilder,
            showSearchField: pickerConfig?.showSearchField,
            subtitleBuilder: pickerConfig?.subtitleBuilder,
            disabledWhen: disabledWhen,
            filterMatcher: pickerConfig?.filterMatcher,
            equalityMatcher: pickerConfig?.equalityMatcher,
            secondaryBuilder: pickerConfig?.secondaryBuilder,
          ) as Future<List<T>?>,
        );
}
