import 'package:flutter/material.dart';

import '../extensions/string_extension.dart' show StringExtension;
import '../extensions/time_of_day_extension.dart';
import '../widgets/date_picker.dart' show showCupertinoTimePicker;
import 'form_field.dart';

/// 时间选择Form组件
class TimePickerFormField extends TxPickerTextFormField<TimeOfDay, TimeOfDay> {
  TimePickerFormField({
    String? initialValue,
    TimeOfDay? initialTime,
    TimeOfDay? minimumTime,
    TimeOfDay? maximumTime,
    String format = 'HH:mm',
    super.key,
    super.onSaved,
    super.validator,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.required,
    super.label,
    super.labelText,
    super.backgroundColor,
    super.direction,
    super.padding,
    List<Widget>? actions,
    super.labelStyle,
    super.starStyle,
    super.horizontalGap,
    super.minLabelWidth,
    super.controller,
    super.prefixIconMergeMode,
    super.suffixIconMergeMode,
    super.focusNode,
    super.decoration,
    super.keyboardType,
    super.textCapitalization,
    super.textInputAction,
    super.style,
    super.strutStyle,
    super.textDirection,
    super.textAlign,
    super.textAlignVertical,
    super.autofocus,
    super.readonly,
    super.maxLines,
    super.minLines,
    super.maxLength,
    super.onChanged,
    super.onTap,
    super.onEditingComplete,
    super.inputFormatters,
    super.showCursor,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLengthEnforcement,
    super.expands,
    super.onTapOutside,
    super.onFieldSubmitted,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorColor,
    super.keyboardAppearance,
    super.scrollPadding,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.buildCounter,
    super.scrollPhysics,
    super.autofillHints,
    super.scrollController,
    super.enableIMEPersonalizedLearning,
    super.mouseCursor,
    super.contextMenuBuilder,
  }) : super(
          labelMapper: (TimeOfDay? time) =>
              time?.formatWithoutLocalization() ?? '',
          valueMapper: (TimeOfDay time) => time,
          initialValue: initialTime ?? initialValue?.toTime(),
          onPickTap: (context, initialTime) => showCupertinoTimePicker(
            context,
            initialTime: initialTime,
            minimumTime: minimumTime,
            maximumTime: maximumTime,
          ),
          actionsBuilder: (field) => actions,
        );
}
