import '../extensions.dart';
import '../utils/basic_types.dart';
import '../widgets/cascade_picker.dart';
import 'common_text_field.dart';

/// 内容为级联选择框的 TxTile
class TxCascadePickerField<T, V> extends TxCommonTextField<T> {
  /// 创建一个级联选择器
  TxCascadePickerField({
    required List<T> source,
    required ValueMapper<T, String?> labelMapper,
    required ValueMapper<T, List<T>?> childrenMapper,
    bool? isParentNodeSelectable,
    super.key,
    super.focusNode,
    super.decoration,
    super.onChanged,
    super.enabled,
    super.clearable,
    String? hintText,
    super.textAlign,
    super.bordered,
    ValueMapper<T, V>? valueMapper,
    T? initialData,
    V? initialValue,
    super.label,
    super.labelText,
    super.labelTextAlign,
    super.labelOverflow,
    super.padding,
    super.actionsBuilder,
    super.labelStyle,
    super.horizontalGap,
    super.tileColor,
    super.layoutDirection,
    super.trailingBuilder,
    super.leading,
    super.visualDensity,
    super.shape,
    super.iconColor,
    super.textColor,
    super.leadingAndTrailingTextStyle,
    super.minLeadingWidth,
    super.minLabelWidth,
    super.minVerticalPadding,
    super.dense,
    super.colon,
    super.focusColor,
    super.controller,
    super.undoController,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlignVertical,
    super.textDirection,
    super.showCursor,
    super.autofocus,
    super.statesController,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onEditingComplete,
    super.onSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.cursorErrorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onTapAlwaysCalled,
    super.onTapOutside,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.restorationId,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contextMenuBuilder,
    super.canRequestFocus,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
  }) : super(
          onTap: (field) async {
            final res = await showCascadePicker<T, V>(
              context: field.context,
              datasource: source,
              labelMapper: labelMapper,
              valueMapper: valueMapper,
              childrenMapper: childrenMapper,
              initialData: field.value,
              isParentNodeSelectable: isParentNodeSelectable,
            );
            if (res != null) {
              field.didChange(res);
            }
          },
          displayTextMapper: (context, val) => labelMapper(val) ?? '',
          initialValue: source.getInitialData<V>(
            initialData: initialData,
            initialValue: initialValue,
            valueMapper: valueMapper,
          ),
          hintText: hintText ?? '请选择',
          readOnly: true,
        );

  TxCascadePickerField.fromMapList({
    required List<Map> source,
    String? labelKey,
    String? valueKey,
    String? idKey,
    String? pidKey,
    String? childrenKey,
    bool? isParentNodeSelectable,
    super.key,
    super.focusNode,
    super.decoration,
    super.onChanged,
    super.enabled,
    super.clearable,
    String? hintText,
    super.textAlign,
    super.bordered,
    Map? initialData,
    V? initialValue,
    super.label,
    super.labelText,
    super.labelTextAlign,
    super.labelOverflow,
    super.padding,
    super.actionsBuilder,
    super.labelStyle,
    super.horizontalGap,
    super.tileColor,
    super.layoutDirection,
    super.trailingBuilder,
    super.leading,
    super.visualDensity,
    super.shape,
    super.iconColor,
    super.textColor,
    super.leadingAndTrailingTextStyle,
    super.minLeadingWidth,
    super.minLabelWidth,
    super.minVerticalPadding,
    super.dense,
    super.colon,
    super.focusColor,
    super.controller,
    super.undoController,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlignVertical,
    super.textDirection,
    super.showCursor,
    super.autofocus,
    super.statesController,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onEditingComplete,
    super.onSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.cursorErrorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onTapAlwaysCalled,
    super.onTapOutside,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.restorationId,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contextMenuBuilder,
    super.canRequestFocus,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
  }) : super(
          initialValue: source.getInitialData<V>(
            initialData: initialData,
            initialValue: initialValue,
            valueMapper: (data) => data[valueKey],
          ) as T?,
          onTap: (field) async {
            final res = await showMapTreeCascadePicker<V>(
              context: field.context,
              datasource: source,
              labelKey: labelKey,
              valueKey: valueKey,
              childrenKey: childrenKey,
              initialData: field.value as Map?,
              isParentNodeSelectable: isParentNodeSelectable,
            );
            if (res != null) {
              field.didChange(res as T);
            }
          },
          displayTextMapper: (context, val) =>
              (val as Map?)?[labelKey ?? kLabelKey] ?? '',
          hintText: hintText ?? '请选择',
          readOnly: true,
        );

  TxCascadePickerField.formMapTree({
    required List<Map> source,
    String? labelKey,
    String? valueKey,
    String? childrenKey,
    bool? isParentNodeSelectable,
    super.key,
    super.focusNode,
    super.decoration,
    super.onChanged,
    super.enabled,
    super.clearable,
    String? hintText,
    super.textAlign,
    super.bordered,
    Map? initialData,
    V? initialValue,
    super.label,
    super.labelText,
    super.labelTextAlign,
    super.labelOverflow,
    super.padding,
    super.actionsBuilder,
    super.labelStyle,
    super.horizontalGap,
    super.tileColor,
    super.layoutDirection,
    super.trailingBuilder,
    super.leading,
    super.visualDensity,
    super.shape,
    super.iconColor,
    super.textColor,
    super.leadingAndTrailingTextStyle,
    super.minLeadingWidth,
    super.minLabelWidth,
    super.minVerticalPadding,
    super.dense,
    super.colon,
    super.focusColor,
    super.controller,
    super.undoController,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlignVertical,
    super.textDirection,
    super.showCursor,
    super.autofocus,
    super.statesController,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onEditingComplete,
    super.onSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.cursorErrorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onTapAlwaysCalled,
    super.onTapOutside,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.restorationId,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contextMenuBuilder,
    super.canRequestFocus,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
  }) : super(
          initialValue: source.getInitialData<V>(
            initialData: initialData,
            initialValue: initialValue,
            valueMapper: (data) => data[valueKey],
          ) as T?,
          onTap: (field) async {
            final res = await showMapTreeCascadePicker<V>(
              context: field.context,
              datasource: source,
              labelKey: labelKey,
              valueKey: valueKey,
              childrenKey: childrenKey,
              initialData: field.value as Map?,
              isParentNodeSelectable: isParentNodeSelectable,
            );
            if (res != null) {
              field.didChange(res as T);
            }
          },
          displayTextMapper: (context, val) =>
              (val as Map?)?[labelKey ?? kLabelKey] ?? '',
          hintText: hintText ?? '请选择',
          readOnly: true,
        );
}
