name: tx_design
description: A custom component library that contains some basic UI components and provides theme configuration.
version: 0.2.11

homepage: https://github.com/cj123195/tx_design.git
repository: https://github.com/cj123195/tx_design
issue_tracker: https://github.com/cj123195/tx_design/issues
documentation: https://github.com/cj123195/tx_design

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2